version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    stdin_open: true
    tty: true
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.6.0'
    depends_on:
      - zookeeper
    stdin_open: true
    tty: true
    ports:
      - '9093:9093'
      - '29092:29092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://193.196.38.1:9093 # Change EXTERNAL URL/IP to outside reacheable address
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  goflow:
    image: cloudflare/goflow:v3.4.1
    stdin_open: true
    tty: true
    ports:
      - '6343:6343/udp'
      - '2055:2055/udp'
    entrypoint: '/bin/sh'
    command: >
      -c "sleep 1m ;
      /goflow -kafka.brokers kafka:9092
      -kafka.topic flows
      -nf=true
      -nf.port 2055"
    depends_on:
      - kafka
  enricher:
    image: ghcr.io/submergedtree/processor-enricher:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_IN_TOPIC: flows
      KAFKA_OUT_TOPIC: flows-enriched
      KAFKA_CONSUMER_GROUP: test-consumer-group
      DISABLE_AUTH: 'true'
      DISABLE_TLS: 'true'
    depends_on:
      - kafka
  mptcp_aggregator:
    image: ghcr.io/submergedtree/mptcp_aggregator:latest
    restart: unless-stopped
    environment:
      BWNETFLOW_INPUT_TOPIC: flows-enriched
      MPTCP_FLOW_INPUT_TOPIC: mptcp-packets
      OUTPUT_TOPIC: mptcp-joined
      KAFKA_ADDRESS: kafka:9092
      JOIN_WINDOW_TIME: 120
      LOG_MPTCP: 'true'
      LOG_FLOW: 'true'
      LOG_JOINED: 'true'
      ADDRESS_WHITELIST: '193.196.37.204,193.196.38.233,192.168.1.220,193.196.38.1,2001:7c0:2310:0:f816:3eff:fe4f:e553,2001:7c0:2310:0:f816:3eff:fe76:45a2'
    depends_on:
      - kafka
